name: Rock Stars Rising
favicon: null
layout_spectrum: 0.7762414764147252
typography_spectrum: 0.24805423943325877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a061c'
    - '#ff0000'
    - '#555262'
    - '#8e9da2'
    - '#e73f1b'
  brandStrength: 0.5
  lightness: 0.779730630107224
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
