name: Rock Stars Rising
favicon: null
layout_spectrum: 0.7762414764147252
typography_spectrum: 0.24805423943325877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7769925114698708
  lightness: 0.779730630107224
  saturation: 0.11550283594988286
  rhythmicContrast: 0.6351552291307598
purpose: []
